version: 2

sources:
  - name: raw
    database: grocery-sales-478511     # replace with your GCP project ID
    schema: grocery_sales_478511          # replace with the BigQuery dataset where Airbyte writes CSVs
    tables:
      - name: sales
      - name: products
      - name: customers
      - name: employees
      - name: cities
      - name: countries
      - name: categories