version: 2

sources:
  - name: raw
    database: grocery-sales-478511
    schema: grocery_sales_478511_grocery_sales  # The actual dataset name in BigQuery
    tables:
      - name: Grocery_Sales  # The main source table